language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install: "cpanm -fi Template::Alloy CGI::Ex perl cgi-bin/ya"
os:
  - linux
  - osx
  - freebsd
osx_image: xcode61
