language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before-install:
  - cpan -fi Template::Alloy CGI::Ex

install: "./ya.pl"
os:
  - linux
  - osx
  - freebsd
osx_image: xcode61
